version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.14.1
    # restart: always
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"
      ELASTIC_PASSWORD: "123456" # 配置密码
    ports:
      - 9200:9200
      - 9300:9300
    volumes: 
      - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/data:/usr/share/elasticsearch/data
      # - ./es/plugins:/usr/share/elasticsearch/plugin